/*
 * generated by Xtext 2.10.0
 */
package io.typefox.vscode.validation

import io.typefox.vscode.myLanguage.TypeDeclaration
import org.eclipse.xtext.validation.Check

import static io.typefox.vscode.myLanguage.MyLanguagePackage.Literals.*

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyLanguageValidator extends AbstractMyLanguageValidator {

	@Check
	def checkTypeExtendsItself(TypeDeclaration type) {
		if (type.superType == type)
			error('A type cannot extend itself', TYPE_DECLARATION__SUPER_TYPE)
	}
	
}
